- README.md
List needs more status pages! 🎉
> Add cState

- README.md
Small broken link fix & Added Statuspal to the list of status page services.
> Fix link + added Statuspal

- README.md
https://github.com/Pryx/server-status
> new php opensource project Server-Status

- README.md
PageFate.com just launched officially with free public status pages that can be customized.
> Added PageFate.com to services

- README.md
PR to add a new Open Source Health Check Tool - https://github.com/tmobile/kardio
> Added Kardio.io

- README.md
1. Remove duplicate for Staytus,
2. Add open source project: statuspage.
> Update open source list

- README.md
> Update list with a-z sorting

- README.md
Adding Uptime Robot 
Updated link name updown.io
> Adding Uptime Robot

- README.md
Thanks for including my Status page system :)
> Add ClearStatus in Opensource section

- README.md
Let me know what you think!
GitHub: https://github.com/tadhglewis/issue-status
Demo: https://tadhglewis.github.io/issue-status
> Add Issue Status

- README.md
Hi, I added [instatus.com](https://instatus.com).
Please let me know if this placement is okay, or if you want me to make any changes. 
Thank you!
> add instatus.com to readme

- README.md
> Added HetrixTools Service

- README.md
Exana Statuspage is not working anymore
> Remove Exana, because it doesn't work anymore

- README.md
Added DigitalOcean and Reddit Status Page links
Closes: #30
> Added DigitalOcean and Reddit Status Page links

- README.md
Statusy is no longer accepting new accounts as they are "sunsetting" the service.
> crossed out statusy and added note of discontinuation

- README.md
+ removed extra whitespace.
Disclosure: I run Hexadecimal
> Add Hexadecimal

- README.md
> Add tinystatus

- README.md
Added the statuspage.io open-sourced version, though it is a couple of years old.
> added the statuspage.io open source CE

- README.md
> Remove asserted.io

- README.md
Added better uptime as a service
> Added better uptime as a service

- README.md
We just built our own Status Page at Statsig and would love to have it listed here. Thanks!
> Add Statsig's Open-Source Status Page

- README.md
Added a few links used for the monitoring status
> A new public status pages

- README.md
Amplitude for the easy click it
> add amplitude

- README.md
As per maintainers message, Statusfy is no longer supported. See: https://github.com/juliomrqz/statusfy/discussions/826
> Statusfly discontinued

- README.md
It will be a great pleasure to join your list of services with Odown which provides beautiful public status pages with built-in monitoring.
> Add Odown.io

- README.md
Last release was more than two years ago
> Consider Cachet as discontinued

- README.md
Fix various typos and correct Google Workspace
> fix various typos

- README.md
> Added Hydrozen.io

- README.md
Squadcast is an Incident Management platform and I have added Squadcast's public Status page link
> Added Squadcast Public Statuspage

- README.md
Adds Okazanta, a fork of Cachet, to the list
> Add Okazanta

- README.md
[Collect more public status pages](#82 )
[Reorganize public status pages by service categories](#81 )
> New section organize and status pages

- README.md
Add django-statusboard to the list.
> Add django-statusboard

- README.md
> Added the new Status Page

- README.md
@ivbeg adding status page for OpenAI and Wikimedia.
> Added OpenAI and Wikimedia status page

- README.md
Greetings,
Thanks for making this list 💐  I am the founder of WebGazer, and I think it can be a good addition.
> Add WebGazer

- README.md
+ added savla-dish (dish) project link
+ fixed the Opensource listings' alphabetical order (mostly)
> add dish, fix Opensource listings' alphabetical order

- README.md
> Add okta status page

- README.md
Okazanta has no active maintainers and no recent activity.
https://github.com/Okazanta/okazanta-legacy/issues/43
Fixes #105
> Okazanta is not maintained

- README.md
> Cachet is back!

- README.md
Hi there! 
Add IsDown.app to the services section, and a couple of status pages to the Hosting & Cloud section. 
Thank you.
> Add IsDown.app & new status pages

- README.md
Recommend UptimeFlare project written by me.
> Add UptimeFlare

- README.md
Small typo corrections and quick fixes
> Update README.md with Small Fixes

- README.md
> add Hibob as a service of HRIS

- README.md
status page using SvelteKit + Node.js with incident management
> Added Kener.ing

- README.md
> add humanity service

- README.md
Hey,
I just added the status page and uptime monitoring service Garmingo Status to the list.
> Added Garmingo Status to the list

- README.md
Added incident.io to the list of services.
> Add incident.io as a service

- README.md
And Linear as an example of incident.io status pages
> Add incident.io

- README.md
hi, this pr add open source project hertzbeat https://github.com/dromara/hertzbeat
> add open source project hertzbeat

- README.md
Hi!
I just added StatusSight to the services list.
> Add StatusSight

- README.md
Added https://incidenthub.cloud/ - a status page aggregator.
> Add IncidentHub

- README.md
Adding Uptime.com to the list.
> Add Uptime.com to README.md

- README.md
Added another open source server-status monitoring tool
> Added aPulse

- README.md
Add StatusRay to the list of services.
> Add StatusRay
